#!/bin/sh

php bin/console doctrine:database:drop --force --env=test
php bin/console doctrine:database:create --env=test
php bin/console doctrine:migrations:migrate --env=test

php bin/console fixtures:load --env=test

php bin/console cache:clear --env=test
php bin/console_backend cache:clear --env=test
php bin/console_frontend cache:clear --env=test

php -d memory_limit=-1 ./bin/phpunit -c ./phpunit-backend.xml
php -d memory_limit=-1 ./bin/phpunit -c ./phpunit-frontend.xml
