# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

admin_area:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /